config/routes.rb
Rails.application.routes.draw do
  resources :work_orders
  resources :clients
  resources :technicians
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
  has_many :work_orders
  has_many :technicians, through: :work_orders
end

app/models/technician.rb
class Technician < ApplicationRecord
  validates :name, presence: true, uniqueness: false, length: {maximum: 15}
  validate :begins_with_x, :y_start

  has_many :work_orders
  has_many :clients, through: :work_orders

  def begins_with_x
    if self.name[0].downcase == "x"
      self.errors.add(:name, "cannot begin with X")
    end
  end

  def y_start
    if self.name[0].downcase == "y"
      self.errors.add(:name, "cannot begin with y")
    end
  end

end

app/models/work_order.rb
class WorkOrder < ApplicationRecord

  validates :jobname, length: {minimum: 5}
  validates :jobname, presence: true

  validate :name_cannot_begin_with_number

  def name_cannot_begin_with_number
    if self.jobname.start_with?("1","2","3","4","5","6","7","8","9","0")
      self.errors.add(:jobname, "Cannot begin with number" )
    end
  end

  belongs_to :technician
  belongs_to :client
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :find_client, only: [:show, :destroy, :edit, :update]

  def index
    @clients = Client.all
  end

  def show
    @orders = @client.work_orders
  end

  def new
    @client = Client.new
  end

  def create
    @client = Client.create(client_params)
    redirect_to clients_path
  end

  def update
    @client.update(client_params)
    redirect_to clients_path
  end

  def destroy
    @client.destroy
    redirect_to clients_path
  end

  private

  def find_client
    @client = Client.find(params[:id])
  end

  def client_params
    params.require(:client).permit(:name)
  end
end

app/controllers/technicians_controller.rb
class TechniciansController < ApplicationController

  before_action :find_technician, only: [:show, :destroy, :edit, :update]

  def index
    @technicians = Technician.all
  end

  def show
    @orders = @technician.work_orders
  end

  def new
    @tech = Technician.new
  end

  def create
    @tech = Technician.create(tech_params)
    redirect_to "/technicians"
  end

  def destroy
    @technician.destroy
    redirect_to technicians_path
  end

  def edit
  end

  def update
    @technician.update(tech_params)
    redirect_to technicians_path
  end


  private

  def find_technician
    @technician = Technician.find(params[:id])
  end

  def tech_params
    params.require(:technician).permit(:name)
  end


end

app/controllers/work_orders_controller.rb
class WorkOrdersController < ApplicationController
  before_action :find_work_order, only: [:show, :update, :destroy, :edit]


  def index
    @orders = WorkOrder.all
  end

  def new
    @order = WorkOrder.new
    @techs = Technician.all
    @clients = Client.all
  end

  def create
    @order = WorkOrder.new(order_params)
    if @order.valid?
      @order.save
      redirect_to @order
    else
      flash[:errors] = @order.errors.full_messages
      redirect_to new_work_order_path
    end
  end

  def show
  end

  def edit
    @techs = Technician.all
    @clients = Client.all
  end

  def update
    if @order.update(order_params)
      redirect_to work_orders_path
    else
      flash[:errors] = @order.errors.full_messages
      redirect_to edit_work_order_path(@order)
    end
  end

  def destroy
    @order.destroy
    redirect_to work_orders_path
  end

  private

  def find_work_order
    @order = WorkOrder.find(params[:id])
  end

  def order_params
    params.require(:work_order).permit(:jobname, :status, :technician_id, :client_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/technicians_helper.rb
module TechniciansHelper
end

app/helpers/work_orders_helper.rb
module WorkOrdersHelper
end

app/views/clients/edit.html.erb
<h1>Editing <%= @client.name %></h1>

<%= form_for @client do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/clients/index.html.erb
<h1>Showing list of clients</h1>
<p>
  <%= link_to "Add new client", new_client_path %> |
  <%= link_to "View technicians", technicians_path %> |
  <%= link_to "View work orders",  work_orders_path %>
</p>
<hr>
<ul>
  <% @clients.each do |tech| %>
    <li><%= link_to tech.name, tech  %></li>
  <% end %>
</ul>

app/views/clients/new.html.erb
<h1>Adding new Client</h1>

<%= form_for @client do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/clients/show.html.erb
<h1>Viewing info for <%= @client.name %></h1>
<p>
  <%= link_to "Go back", clients_path %> |
  <%= link_to "Edit #{@client.name}", edit_client_path %> |
  <%= link_to "Delete #{@client.name}", client_path(@client), method: :delete %>
</p>
<hr>
<h3>List of jobs</h3>
<ul>
  <% @orders.each do |order| %>
    <li><%= link_to order.jobname, order %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsPcDoctors</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </head>

  <body>
  <div class="container">
    <div class="row">
      <div class="col-md-6 offset-md-3">
        <%= yield %>
      </div>
    </div>
  </div>
  </body>
</html>

app/views/technicians/edit.html.erb
<h1>Editing <%= @technician.name %></h1>

<%= form_for @technician do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/technicians/index.html.erb
<h1>Showing list of technicians</h1>
<p>
  <%= link_to "Add new technician", new_technician_path %> |
  <%= link_to "View Clients", clients_path %> |
  <%= link_to "View work orders",  work_orders_path %>
</p>
<hr>
<ul>
  <% @technicians.each do |tech| %>
  <li><%= link_to tech.name, tech  %></li>
  <% end %>
</ul>

app/views/technicians/new.html.erb
<h1>Adding new technician</h1>

<%= form_for @tech do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/technicians/show.html.erb
<h1>Viewing info for <%= @technician.name %></h1>
<p>
  <%= link_to "Go back", "/technicians" %> |
  <%= link_to "Edit #{@technician.name}", edit_technician_path %> |
  <%= link_to "Delete #{@technician.name}", technician_path(@technician), method: :delete %>
</p>
<hr>
<h3>List of jobs</h3>
<ul>
  <% @orders.each do |order| %>
  <li><%= link_to order.jobname, order %></li>
  <% end %>
</ul>

app/views/work_orders/edit.html.erb
<h1>Editing <%= @order.jobname %></h1>
<p>
  <%= link_to "Cancel", work_orders_path %> |
  <%= link_to "Delete order", work_order_path(@order), method: :delete %>
</p>

<hr>
<% if flash[:errors] %>
<ul>
  <% flash[:errors].each do |message| %>
  <li><%= message %></li>
  <% end %>
</ul>
  <hr>
<% end %>

<%= form_for @order do |o| %>

  <p><%= o.label :jobname %>
    <%= o.text_field :jobname %></p>

  <p><%= o.label :client_id %>
    <%= o.collection_select(:client_id, @clients, :id, :name) %></p>

  <p><%= o.label :technician_id %>
    <%= o.collection_select(:technician_id, @techs, :id, :name) %></p>

  <p>
    <%= o.label :status %>
    <%= o.radio_button :status, "In progress" %> In progress |
    <%= o.radio_button :status, "Complete" %> Complete
  </p>

  <%= o.hidden_field :id, value: @order.id %>

  <%= o.submit %>
<% end %>

app/views/work_orders/index.html.erb
<h1>Showing <%= @orders.count %> work orders</h1>
<p>
  <%= link_to "Add new work order", new_work_order_path %> |
  <%= link_to "View technicians", technicians_path %> |
  <%= link_to "View clients",  clients_path %>
</p>
<hr>
<ul>
  <% @orders.each do |order| %>
    <li><%= link_to "#{order.jobname} for #{order.client.name} by #{order.technician.name}", order  %></li>
  <% end %>
</ul>

app/views/work_orders/new.html.erb
<h1>Adding new work order</h1>
<p>
  <%= link_to "Cancel", work_orders_path %> |
</p>

<hr>
<% if flash[:errors] %>
  <ul>
    <% flash[:errors].each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
  <hr>
<% end %>

<%= form_for @order do |o| %>

  <p><%= o.label :jobname %>
  <%= o.text_field :jobname %></p>

  <p><%= o.label :client_id %>
  <%= o.collection_select(:client_id, @clients, :id, :name) %></p>

  <p><%= o.label :technician_id %>
  <%= o.collection_select(:technician_id, @techs, :id, :name) %></p>

  <%= o.hidden_field :status, value: "In progress" %>

  <%= o.submit %>

<% end %>

app/views/work_orders/show.html.erb
<h1>Viewing <%= @order.jobname %></h1>
<p>
  <%= link_to "Go back", work_orders_path %> |
  <%= link_to "Edit order", edit_work_order_path %>
</p>
<hr>

<p>Technician: <%= @order.technician.name %></p>
<p>Client: <%= @order.client.name %></p>
<p>Status: <%= @order.status %></p>